import AppKit
import CryptoKit
import Vision

final class ClipboardMonitor {
    private let store: Store
    private var timer: Timer?
    private var lastChangeCount: Int
    private var selfWriteChangeCount: Int = -1
    var paused = false

    /// Catch-all mode: archive every pasteboard type verbatim so app-private
    /// data (Logic Pro regions, etc.) can be restored byte-for-byte.
    var catchAll = UserDefaults.standard.bool(forKey: "catchAll") {
        didSet { UserDefaults.standard.set(catchAll, forKey: "catchAll") }
    }

    /// Per-item cap for raw archives (10 MB).
    static let rawSizeLimit = 10 * 1024 * 1024

    // Pasteboard flags used by password managers / clipboard tools.
    private static let skipTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("com.typeit4me.clipping"),
    ]

    init(store: Store) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        let t = Timer(timeInterval: 0.35, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    /// Call right after this app writes to the pasteboard so we don't re-record it.
    func markSelfWrite() {
        selfWriteChangeCount = NSPasteboard.general.changeCount
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard !paused, lastChangeCount != selfWriteChangeCount else { return }

        let types = pb.types ?? []
        if Self.skipTypes.contains(where: types.contains) { return }
        guard !types.isEmpty else { return }

        let front = NSWorkspace.shared.frontmostApplication
        let appName = front?.localizedName
        let bundleID = front?.bundleIdentifier

        if catchAll, captureRaw(pb, types: types, appName: appName, bundleID: bundleID) {
            return
        }
        captureStandard(pb, types: types, appName: appName, bundleID: bundleID)
    }

    // MARK: - Catch-all capture

    /// Archives every type on the pasteboard verbatim. Returns false (falling
    /// back to standard capture) if the total exceeds the size cap or nothing
    /// could be read.
    /// Archives the pasteboard verbatim: every item, every type, in original
    /// order. Returns false (falling back to standard capture) if the total
    /// exceeds the size cap or nothing could be read.
    private func captureRaw(_ pb: NSPasteboard, types: [NSPasteboard.PasteboardType],
                            appName: String?, bundleID: String?) -> Bool {
        var archive: [[RawBlob]] = []
        var total = 0
        for pbItem in pb.pasteboardItems ?? [] {
            var blobs: [RawBlob] = []
            for t in pbItem.types {
                guard let data = pbItem.data(forType: t) else { continue }
                total += data.count
                if total > Self.rawSizeLimit { return false }
                blobs.append(RawBlob(t: t.rawValue, d: data))
            }
            if !blobs.isEmpty { archive.append(blobs) }
        }
        guard !archive.isEmpty else { return false }

        var hasher = SHA256()
        for blobs in archive {
            for blob in blobs {
                hasher.update(data: Data(blob.t.utf8))
                hasher.update(data: blob.d)
            }
        }
        let hash = hasher.finalize().map { String(format: "%02x", $0) }.joined()
        let filename = hash + ".json"
        let url = store.rawDir.appendingPathComponent(filename)
        if !FileManager.default.fileExists(atPath: url.path) {
            if let data = try? JSONEncoder().encode(archive) {
                try? data.write(to: url)
            }
        }

        // Pick the friendliest preview available; paste always restores everything.
        var type = ClipType.raw
        var text: String? = nil
        var imageFile: String? = nil

        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            type = .file
            text = urls.map(\.path).joined(separator: "\n")
        } else if types.contains(.tiff) || types.contains(.png),
                  let data = pb.data(forType: .png) ?? pb.data(forType: .tiff),
                  let rep = NSBitmapImageRep(data: data),
                  let png = rep.representation(using: .png, properties: [:]) {
            type = .image
            imageFile = Self.hash(png) + ".png"
            let imgURL = store.imagesDir.appendingPathComponent(imageFile!)
            if !FileManager.default.fileExists(atPath: imgURL.path) {
                try? png.write(to: imgURL)
            }
        } else if let str = pb.string(forType: .string),
                  !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            type = Self.isURLString(str) ? .url : .text
            text = str
        } else {
            // No previewable representation — show the type identifiers.
            var seen = Set<String>()
            text = archive.flatMap { $0.map(\.t) }.filter { seen.insert($0).inserted }
                .joined(separator: "\n")
        }

        let item = ClipItem(type: type, text: text, imageFile: imageFile,
                            rawFile: filename, rawSize: total,
                            appName: appName, bundleID: bundleID,
                            contentHash: hash)
        store.add(item)
        if let imageFile {
            runOCR(fileURL: store.imagesDir.appendingPathComponent(imageFile), itemID: item.id)
        }
        return true
    }

    // MARK: - Standard capture

    private func captureStandard(_ pb: NSPasteboard, types: [NSPasteboard.PasteboardType],
                                 appName: String?, bundleID: String?) {
        // 1. File URLs
        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path).joined(separator: "\n")
            store.add(ClipItem(type: .file, text: paths,
                               appName: appName, bundleID: bundleID,
                               contentHash: Self.hash(paths.data(using: .utf8)!)))
            return
        }

        // 2. Images
        if types.contains(.tiff) || types.contains(.png) {
            let data = pb.data(forType: .png) ?? pb.data(forType: .tiff)
            if let data,
               let rep = NSBitmapImageRep(data: data),
               let png = rep.representation(using: .png, properties: [:]) {
                let hash = Self.hash(png)
                let filename = hash + ".png"
                let url = store.imagesDir.appendingPathComponent(filename)
                if !FileManager.default.fileExists(atPath: url.path) {
                    try? png.write(to: url)
                }
                let item = ClipItem(type: .image, imageFile: filename,
                                    appName: appName, bundleID: bundleID,
                                    contentHash: hash)
                store.add(item)
                runOCR(fileURL: url, itemID: item.id)
                return
            }
        }

        // 3. Text / URL
        if let str = pb.string(forType: .string),
           !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            store.add(ClipItem(type: Self.isURLString(str) ? .url : .text, text: str,
                               appName: appName, bundleID: bundleID,
                               contentHash: Self.hash(str.data(using: .utf8)!)))
        }
    }

    /// Ingest an image file (e.g. a new screenshot): add to history as a file
    /// item with an image preview, OCR it, and optionally put the file
    /// reference on the clipboard (like Finder's Cmd+C).
    func ingestImageFile(_ fileURL: URL, appName: String, bundleID: String?, copyToClipboard: Bool) {
        guard let data = try? Data(contentsOf: fileURL),
              let rep = NSBitmapImageRep(data: data),
              let png = rep.representation(using: .png, properties: [:]) else { return }
        let hash = Self.hash(png)
        let previewName = hash + ".png"
        let previewURL = store.imagesDir.appendingPathComponent(previewName)
        if !FileManager.default.fileExists(atPath: previewURL.path) {
            try? png.write(to: previewURL)
        }
        let item = ClipItem(type: .file, text: fileURL.path, imageFile: previewName,
                            appName: appName, bundleID: bundleID,
                            contentHash: hash)
        store.add(item)
        runOCR(fileURL: previewURL, itemID: item.id)
        if copyToClipboard {
            let pb = NSPasteboard.general
            pb.clearContents()
            pb.writeObjects([fileURL as NSURL])
            markSelfWrite()
        }
    }

    /// Recognize text in a captured image (on-device, Vision framework) and
    /// attach it to the item so image contents are searchable.
    private func runOCR(fileURL: URL, itemID: UUID) {
        DispatchQueue.global(qos: .utility).async { [weak self] in
            let request = VNRecognizeTextRequest()
            request.recognitionLevel = .accurate
            request.usesLanguageCorrection = true
            let handler = VNImageRequestHandler(url: fileURL, options: [:])
            try? handler.perform([request])
            let text = (request.results ?? [])
                .compactMap { $0.topCandidates(1).first?.string }
                .joined(separator: " ")
            guard !text.isEmpty else { return }
            DispatchQueue.main.async {
                self?.store.setOCR(id: itemID, text: text)
            }
        }
    }

    private static func isURLString(_ str: String) -> Bool {
        let trimmed = str.trimmingCharacters(in: .whitespacesAndNewlines)
        return !trimmed.contains("\n") && !trimmed.contains(" ")
            && (trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://"))
    }

    private static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
