#!/bin/zsh
# Local development build of PasteStack.app (this Mac's architecture only).
# No Xcode required — Command Line Tools are enough. To ship a release to
# everyone's in-app updater, use ./release.sh instead.
set -e
cd "$(dirname "$0")"
VERSION=$(cat VERSION)
BUILT=$(date "+%b %d, %H:%M")
FEED="${UPDATE_FEED-https://raw.githubusercontent.com/jonpikereally/PasteStack/main/updates/latest.json}"
cat > Sources/PasteStack/Version.swift <<SWIFT
// Generated by build.sh / release.sh — do not edit.
enum AppVersion {
    static let version = "$VERSION"
    static let built = "$BUILT"
    static let updateFeed = "$FEED"
}
SWIFT
CACHE="${TMPDIR:-/tmp}/pastestack-modcache"
mkdir -p "$CACHE" PasteStack.app/Contents/MacOS
cp Resources/Info.plist PasteStack.app/Contents/Info.plist
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" PasteStack.app/Contents/Info.plist
swiftc -O -module-cache-path "$CACHE" -o PasteStack.app/Contents/MacOS/PasteStack Sources/PasteStack/*.swift
codesign --force --sign - PasteStack.app
echo "Built PasteStack.app v$VERSION ($BUILT)"
