#!/bin/zsh
# Build a release: universal (Apple Silicon + Intel) app with an installer,
# written to updates/PasteStack.zip + updates/latest.json. Committing and
# pushing updates/ ships it: every installed copy's "Check for Updates" reads
# latest.json from this repo on GitHub.
#   UPDATE_NOTES="What changed" ./release.sh
set -e
cd "$(dirname "$0")"
VERSION=$(cat VERSION)
BUILT=$(date "+%b %d, %H:%M")
FEED="${UPDATE_FEED-https://raw.githubusercontent.com/jonpikereally/PasteStack/main/updates/latest.json}"
cat > Sources/PasteStack/Version.swift <<SWIFT
// Generated by build.sh / release.sh — do not edit.
enum AppVersion {
    static let version = "$VERSION"
    static let built = "$BUILT"
    static let updateFeed = "$FEED"
}
SWIFT
CACHE="${TMPDIR:-/tmp}/pastestack-modcache"
mkdir -p "$CACHE"
echo "Building arm64…"
swiftc -O -target arm64-apple-macos13 -module-cache-path "$CACHE" \
  -o "$CACHE/PasteStack-arm64" Sources/PasteStack/*.swift
echo "Building x86_64…"
swiftc -O -target x86_64-apple-macos13 -module-cache-path "$CACHE-x86" \
  -o "$CACHE/PasteStack-x86_64" Sources/PasteStack/*.swift

DIST="$CACHE/dist"
rm -rf "$DIST"
APP="$DIST/PasteStack/PasteStack.app"
mkdir -p "$APP/Contents/MacOS"
lipo -create -output "$APP/Contents/MacOS/PasteStack" \
  "$CACHE/PasteStack-arm64" "$CACHE/PasteStack-x86_64"
cp Resources/Info.plist "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" "$APP/Contents/Info.plist"
codesign --force --sign - "$APP"

cat > "$DIST/PasteStack/Install PasteStack.command" <<'INSTALL'
#!/bin/bash
# PasteStack installer — copies the app to ~/Applications and launches it.
cd "$(dirname "$0")"
echo "Installing PasteStack…"
mkdir -p ~/Applications
rm -rf ~/Applications/PasteStack.app
ditto --norsrc PasteStack.app ~/Applications/PasteStack.app
# Clear the download quarantine and re-sign locally so macOS trusts it on this Mac.
xattr -dr com.apple.quarantine ~/Applications/PasteStack.app 2>/dev/null
codesign --force --sign - ~/Applications/PasteStack.app
open ~/Applications/PasteStack.app
echo
echo "Done! Look for the clipboard icon in your menu bar."
echo "Grant the Accessibility permission when asked — that lets PasteStack"
echo "paste for you automatically. Then press Shift+Cmd+V anywhere."
INSTALL
chmod +x "$DIST/PasteStack/Install PasteStack.command"

cat > "$DIST/PasteStack/README.txt" <<README
PasteStack v$VERSION — a free, local clipboard manager for macOS (13+)
https://github.com/jonpikereally/PasteStack

INSTALL
1. Double-click "Install PasteStack.command".
   If macOS blocks it: right-click it, choose Open, then Open again.
2. Grant the Accessibility permission when prompted (System Settings →
   Privacy & Security → Accessibility). This lets PasteStack paste for you.

USE
• Shift+Cmd+V — open your clipboard history (card wall at bottom of screen)
• Type to search — content, text inside images (OCR), app, kind ("pdf",
  "image", "link"), or day ("yesterday", "monday")
• Arrow keys + Return to paste (Shift+Return = plain text), Esc to close
• Double-click a card to paste it; right-click for more options
• Pin favorites to Pinboards (right-click a card) — they never expire
• Menu bar icon: pause, catch-all capture, copy new screenshots to the
  clipboard, open at login, check for updates

PRIVACY
Your clipboard history stays on your Mac
(~/Library/Application Support/PasteStack). No accounts, no analytics.
The only thing PasteStack fetches from the internet is a small version file
from the GitHub repo above, to see whether an update exists. Copies from
password managers are never recorded.
README

mkdir -p updates
(cd "$DIST" && ditto -c -k --norsrc --noextattr --noqtn --keepParent PasteStack "$OLDPWD/updates/PasteStack.zip.tmp")
mv -f updates/PasteStack.zip.tmp updates/PasteStack.zip
# Manifest last, so a checking app never sees it pointing at a half-written zip.
/usr/bin/python3 -c 'import json,sys; print(json.dumps({"version": sys.argv[1], "url": "PasteStack.zip", "notes": sys.argv[2]}))' \
  "$VERSION" "${UPDATE_NOTES:-}" > updates/latest.json.tmp
mv -f updates/latest.json.tmp updates/latest.json

./build.sh >/dev/null
echo "Release v$VERSION written to updates/. Ship it with:"
echo "  git add -A && git commit -m \"Release v$VERSION\" && git push"
